[server]
headless = true
enableXsrfProtection = false
enableCORS = false
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#1B365D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
